config = {
    'exp_name' : 'experimental_name',
    'epoch' : 200,
    'lr' : 1,
    'batch' : 4,
    'val_frequency' : 1,
    'test_only' : False,
    'resume' : 'model_path',
    'train_dataset' : 'path_to_traing_datasets',
    'test_dataset': 'path_to_testing_datasets',
    'schedule_frequency' : 15,
    'imageH' : 64,
    'imageW' : 200,
    'alpha_path' : './data/alphabet.txt',
    'max_len' : 60,
}
